### ISSUE TITLE
Zoom overlaping

### ISSUE THREAD

**Issue by free-x** [quantenschaum/mapping#4] opened 2024-01-25 19:02 UTC
Hi,

is it possible to extend zooms? So that if no data is available, the "tiles" from larger zoom levels should be used
For example:
Overview 7-9
General 9-11
Coastal 11-13
Approach 13-15
Harbour 15-17

Now it looks a little confusing
For example
Zoom 11
![image](https://github.com/quantenschaum/mapping/assets/1073657/135edf50-23a1-4ca6-af74-ef67655ac30e)
Zoom 12
![image](https://github.com/quantenschaum/mapping/assets/1073657/cebd831c-0c93-4a36-8986-561d77d4386f)

**Comment by quantenschaum** [comment] 2024-01-25 19:34
I know, but this is not trivial afaik. QGIS does not know about tiles, it just has vector data with assigned zoom levels. You want data of one zoom level only to be displayed at a time, except if an area where there is no data at this zoom level. You don't want to mix data from different levels, it's a mess. There are even features representing the real object, but they are in different locations on the map in different usage bands.

Since the "skin of earth" layer covers the entire chart area, one could duplicate the layers and put over one another. But it's kind of ugly. An better ideas?

**Comment by quantenschaum** [comment] 2024-01-25 19:43
But there is no chart border at the location shown in the screen shot. These are just missing tiles. Try to reload.

**Comment by quantenschaum** [comment] 2024-01-25 19:53
good example with all zoom levels is Heiligenhafen

**Comment by quantenschaum** [comment] 2024-01-26 08:57
using the `scamax/scamin` fields to determine at which scale a feature gets shown does not work at all. 

- `scamax<scamin` because they contain the denominator of the map scale (higher zoom level = lower `@map_scale`, reads like `1/scamin<1/scamax`) :exploding_head: 
- `scamin` sets the lower bound for the zoom level (hide below this level, hence "min"), but can be `null` :exclamation: 
- `scamax` sets the upper bound for zoom level (hide above this level, hence "max"), seems never to be `null` and corresponds to [usage band](https://www.nauticalcharts.noaa.gov/charts/rescheming-and-improving-electronic-navigational-charts.html)

The condition 

```sql
scamax<=@map_scale and (@map_scale<scamin or scamin is null)
```

yields totally cluttered maps because features with `scamin=null` are shown at lower zoom levels. And, since the scale ranges defined by `scamin/scamax` do overlap, you get *duplicate* features on the map, wich makes the map really confusing, i.e. doubled contour lines:

![image](https://github.com/quantenschaum/mapping/assets/3985599/ac7e4e07-5022-421d-ab70-306b95a03c6e)


So, there must only be data shown from a *single* usage band at a time!

**Comment by free-x** [comment] 2024-01-26 12:45
The whole debacle looks very good in Brunsbüttel
z11
![image](https://github.com/quantenschaum/mapping/assets/1073657/27cabb76-dd83-4c26-b1a5-286ddc8c18bd)
z12
![image](https://github.com/quantenschaum/mapping/assets/1073657/b52957cb-76a2-4adf-9fca-0504ce4c8a98)
z13
same empty picture
z14
![image](https://github.com/quantenschaum/mapping/assets/1073657/30a7b6f7-9615-4f40-93f6-947eaa21e947)

**Comment by quantenschaum** [comment] 2024-01-26 13:58
I know, it's explained above. You cannot mix usage bands without generating a mess on the chart. And I did not find a way yet in QGIS to automatically switch usage bands based on zoom levels, but display data from another usage band *below* the current layer if there is no data.

**Comment by quantenschaum** [comment] 2024-01-26 14:05
A workaround is to serve the map twice (slow!)

1. the original
2. a copy with shifted usage bands

Now both maps are combined by mapproxy, the shifted map showing a lower usage band below the main map. So you can overzoom by one band. It seem impossible to pass an additional parameter to QGIS server with the request, is it?

**Comment by quantenschaum** [comment] 2024-01-26 17:01
There are cases overlapping charts of the same usage band. :grimacing: 

![image](https://github.com/quantenschaum/mapping/assets/3985599/af1ef974-94c1-4c2c-a32f-5998022b2161)

Kalkgrund UB=3, that should not happen, the problem is the old chart DE16001 that has not yet been [reschemed](https://www.nauticalcharts.noaa.gov/charts/rescheming-and-improving-electronic-navigational-charts.html).

**Comment by quantenschaum** [comment] 2024-01-26 22:38
The problem of overlapping charts can be solved like this:

1. for a given area, select all charts that intersect with this area
2. render each chart one by one, ordered by usage band
3. the resulting mosaic of charts is the "correct" combination of these charts

I don't know how to do this in QGIS. Any suggestions?

**Comment by free-x** [comment] 2024-01-27 11:02
Pulled cab2cc981c797c201be7a0b13c5c48d2b72f71ea and run seed overnight.
mbtiles has grown threefold. The gaps have become much smaller. In some places the colors are distorted and symbols overlap. 

Don't know how is better

**Comment by quantenschaum** [comment] 2024-01-27 14:12
Of course it gets bigger with more tiles.

Do you have an image if distorted colours and overlapping symbols?

**Comment by free-x** [comment] 2024-01-27 14:20
e.g.
![image](https://github.com/quantenschaum/mapping/assets/1073657/1eedb8e8-5bd6-4e57-9956-3c27627daba5)

**Comment by quantenschaum** [comment] 2024-01-27 16:01
Looks good, the colours seem distorted because the land area is semi transparent (to use the map as overlay for OSM). So it works as expected.

**Comment by free-x** [comment] 2024-01-28 16:06
take a look at Hamburg
z10
![image](https://github.com/quantenschaum/mapping/assets/1073657/78c60f2a-a2b2-4414-9282-61ce758cf34c)
z11
![image](https://github.com/quantenschaum/mapping/assets/1073657/db3a11d6-05c4-4903-8407-e2c6939b337e)
z12
![image](https://github.com/quantenschaum/mapping/assets/1073657/8fa4354b-b578-4728-a2d6-e5028d4bfc61)
z13
![image](https://github.com/quantenschaum/mapping/assets/1073657/8c4e449a-1901-4cf4-b6f3-4b4e423ef98b)
z14-15 
empty
z16
perfect
![image](https://github.com/quantenschaum/mapping/assets/1073657/3a2544c4-f4ac-4a4e-aa05-e442df8285a4)

**Comment by quantenschaum** [comment] 2024-01-28 18:42
I know, this seems unpleasant, but it is like this due to the way the charts are structured. The ENCs were desigend/copied from the old paper charts, which had these coverages (afaik).

Each usage band is assigned to several zoom levels (see [`seed.yaml`](https://github.com/quantenschaum/mapping/blob/master/seed.yaml)). Now there are regions like Hamburg, where the city is covered on UB 1 and 4-5 but not on UB 2-3. This is why there is a "hole in the map".

The data does not allow it to display data from different UBs at once. It will clutter up the chart and duplicate features would even make it confusing or misleading. So this is not an option. I solved this by serving the map twice from MapProxy consisting of two layers. The lower layer shows the tiles from the previous UB, the upper layer shows the current UB. This covers cases where one UB is missing and allows to overzoom. Since the layers are not transparent (at least the water), if there is data present in on layer, it will cover the layers below.

In the case of several missing UBs, there will be no data at some zoom levels. One could another lower below these two layers showing the next UB, but this makes rendering even slower. 

I would like to solve this in QGIS, but I did not find a way to do this. Any ideas?

(I think, the oCharts plugin does it in a similar manner, which leads to very cluttered maps sometimes. I set underzoom=0.)

**Closed as completed** 2024-02-11 13:54 UTC
